# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d75e7b8ee43f0b18f7cda5792f80ce0b7fe75d8117bb5e2278925d022a183400d0bdaefebe0572a5a30394c9a604617a69fb8b12a9130e4cabccf312daa6bd6

test:
  secret_key_base: 8e5936c0d1ab7adb2ace160554e82f04dcd77218d87065536129bb09034aa736fe86570faa1fc4b3d9cc4fd98f3bd871962d865158bbdfdc179998fba576edbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
